server:
  port: 8082

spring:
  application:
    name: foodybuddy-payments
  datasource:
    url: jdbc:postgresql://localhost:5432/foodybuddy?currentSchema=payments
    driverClassName: org.postgresql.Driver
    username: foodybuddy_user
    password: foodybuddy_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: payments

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.foodybuddy.payments: DEBUG

# Payment processing configuration
payment:
  processing:
    timeout: 30000  # 30 seconds
    retry-attempts: 3
    success-rate: 0.9  # 90% success rate for simulation
  simulation:
    enabled: true
    processing-delay: 2000  # 2 seconds delay
