server:
  port: 8082

spring:
  application:
    name: foodybuddy-payments
  datasource:
    url: jdbc:h2:mem:paymentsdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.foodybuddy.payments: DEBUG

# Payment processing configuration
payment:
  processing:
    timeout: 30000  # 30 seconds
    retry-attempts: 3
    success-rate: 0.9  # 90% success rate for simulation
  simulation:
    enabled: true
    processing-delay: 2000  # 2 seconds delay
