server:
  port: 8082

spring:
  application:
    name: foodybuddy-payments
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres-db-service}:${DB_PORT:5432}/${DB_NAME:foodybuddy}?currentSchema=${DB_SCHEMA_PAYMENTS:payments}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:foodybuddy_user}
    password: ${DB_PASSWORD:foodybuddy_password}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: payments

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.foodybuddy.payments: ${LOG_LEVEL_PAYMENTS:INFO}
  pattern:
    console: "${LOG_PATTERN_CONSOLE:%d{yyyy-MM-dd HH:mm:ss} - %msg%n}"

# Payment processing configuration
payment:
  processing:
    timeout: ${PAYMENT_TIMEOUT:30000}  # 30 seconds
    retry-attempts: ${PAYMENT_RETRY_ATTEMPTS:3}
    success-rate: ${PAYMENT_SUCCESS_RATE:0.9}  # 90% success rate for simulation
  simulation:
    enabled: ${PAYMENT_SIMULATION_ENABLED:true}
    processing-delay: ${PAYMENT_PROCESSING_DELAY:2000}  # 2 seconds delay
